### ISSUE TITLE
Utmana - ändringar i meddelandetexten slår inte igenom

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#1]
När man väljer att utmana någon får man upp ett förifyllt meddelandefältet. I detta kan man, till synes, ändra meddelandetexten. När man är klar och klickar på OK går meddelandet iväg men med den ursprungliga förifyllda texten, utan de ändringar man gjort. Inte bra. Detta gör att vi inte kan använda funktionen Utmana till att planera in när kommande matcher ska spelas.

**Comment by Ekryd** [comment]
Det här är en bug och ska fixas pronto. Prio 1 till nästa leverans

**Comment by Ekryd** [comment]
Fixat.

**Comment by jj71** [comment]
Skulle vara bättre om du lägger issuen i status Fixed på mig för verifikation. Inte optimalt att utvecklaren testar och stänger issues själv.
