### ISSUE TITLE
Regler - stegregler under egen flik

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#10]
Reglerna för Stegen bör finnas på sidan och under en egen flik. Fliken bör förslagsvis heta "Regler" och innehålla texten:

Vi spelar matcher om bäst av fem set (först till tre).
Varje set ger en poäng, alltså spelar vi om fem poäng i varje match.
1. Om vinnaren i en match är den högre rankade (har högst poäng av de två) får denne 5 poäng minus det antal set som förloraren vinner. Förloraren får 1 poäng för varje set den vinner. Poängen man får läggs till den innevarande poängen.
2. Om vinnaren är den lägre rankade (har lägst poäng av de två) ersätts dennes innevarande poäng av den poängen som motståndaren hade innan matchstart plus 5 poäng minus det antal set som förloraren vinner. Förloraren behåller sin innevarande poäng och får 1 poäng för varje set den vinner.

Alltså:
En 3-0 match ger 5p till vinnaren och 0p till förloraren.
En 3-1 match ger 4p till vinnaren och 1p till förloraren.
En 3-2 match ger 3p till vinnaren och 2p till förloraren.

Exempel 1:
Anders har 41p, Peter har 28p
Anders slår Peter med 3-2
Anders får 41 + (5-2) = 44p
Peter får 28 + 2 = 30p

Exempel 2:
Kalle har 22p, Pelle har 32p
Kalle slår Pelle med 3-1
Kalle får 32 + (5-1) = 36p
Pelle får 32 + 1 = 33p

Det lönar sig alltså att spela många matcher och att vinna stort.
Till detta gäller att man endast får utmana någon som ligger 3 steg upp.
Man får endast tacka nej till en utmaning 1 gång. Vid ett andra nekande räknas matchen förlorad med 3-0.

**Comment by askeew** [comment]
committat i hos mig

**Comment by askeew** [comment]
björne, nu när jag realiserat denna issue... kan man sätta den till fixed/resolved eller nåt? close?

**Comment by Ekryd** [comment]
Det blir Jimmy som kommer att testa och stänga den när version 12 kommer ut. Sätter över den på Jimmy så får den ligga där tills release.

**Comment by jj71** [comment]
Har verifierat denna i pingisstegen.appspot.com.
Ok.
