### ISSUE TITLE
Spelarkarraktäristik - visa spelares egenskaper

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#11]
Möjlighet att visa spelarkarraktäristiken för varje spelare. Ex. Emil Persson; fart 8, skruv 3, kontroll 5.
Var detta skall visas är inte klart. Kan tänkas att detta kan presenteras tillsammans med en spelarbil, poängsnitt, ranking m.m.
Ska länka till prototyp så fort den är klar.

**Comment by Ekryd** [comment]
Beroende på #21
