### ISSUE TITLE
Trend -  visa trenden för spelarna

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#12]
Att man kan se trenden för spelarna. Kanske en pil som pekar upp, åt sidan eller ned beroende på hur det har gått de senaste matcherna. Björn, vi pratade om denna issue tidigare och du gjorde några anteckningar om/över detta.
Kan du komplettera med de uppgifterna?!
Var skall denna trend vara synlig?

**Comment by joinjohan** [comment]
Jag håller med! Vore kul att se om man kan se formen på den man ska utmana!

**Comment by Ekryd** [comment]
Beroende på #21
