### ISSUE TITLE
Radavstånd - ej enhetligt radavstånd

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#13]
Under de olika flikarna: Poängställning, Meddelanden, Matcher, Inloggning och Övrigt är både radlängden och radavståndet olika för varje flik. Det gör ett rörigt intryck. Radlängd och radavstånd bör enhetliggöras.
Kan åskådliggöra med skärmdump på wikin om så önskas.

**Comment by Ekryd** [comment]
Radavståndet är en förmodligen en bug i FireFox och det har jag fixat till i version 11. Jämför gärna utseendet med Chrome.

**Comment by jj71** [comment]
Använder inte FireFox utan IE.
Jag tror att skillnaden i radavstånd beror på:
1. Under flik poängställning finns knappar som behöver ett visst utrymme i höjdled som är något större än bara text.
2. Under flik Meddelanden är kolumnen för smal för Utfört av och Datum så att en rad skrivs på två rader.
Detta resulterar i att det under de olika flikarna finns tre olika radbredder.

**Comment by Ekryd** [comment]
Då ska du inte använda FireFox, får då får du fyra radhöjder :-)
Vad sägs om att alltid fixa konstanta bredder för Utfört av samt Datum? Det vore synd att begränsa meddelandetexten (och det är dom som kommer att styra höjden). Kan titta på den generella minimum-höjden på rader ochså

**Comment by jj71** [comment]
Konstant bredd låter som en bra lösning. Utfört av bör ha samma bredd som Spelare under fliken Poängställning.
Nej, meddelandetexten bör inte begränsas.

**Comment by Ekryd** [comment]
Verkar faktiskt som jag har begränsat meddelandelängden sedan tidigare. Måste vara någon valideringsiver en sen kväll. Texten är begränsad till 100 tecken.

**Comment by Ekryd** [comment]
Fixat konstanta bredder på spelare och på datum. Fixat i version 11

**Comment by jj71** [comment]
Nu ser det riktigt bra ut! :)
Det är bara förstafliken "Poängställning" som har något större radhöjd men den måste vara större pga knapparna.
Kolumnbredden bra!
