### ISSUE TITLE
Registreringslösenordet är för "smalt", ett mer generellt lösen önskas

### ISSUE THREAD

**Issue by askeew** [Ekryd/Vinnarstegen#14]

**Comment by Ekryd** [comment]
Lägg lösenordet på serversidan och ladda från en propertyfil.

**Comment by askeew** [comment]
Kan du förklara lite mer hur detta är tänkt att gå till? Jag har lite dålig koll på "serversidan" i en GWT-app. 
Vill du ha lösenordet i en propertiesfil i /src/ så den hamnar i war/WEB-INF/classes och därmed ligger på classpath?
