### ISSUE TITLE
Radera användare

### ISSUE THREAD

**Issue by askeew** [Ekryd/Vinnarstegen#17]
En del användare är så pass inaktiva att de säkert blir bättre att ta bort dem så man har aktiva användare. Vore bra att kunna administrera användare, t ex att kunna ta bort dem

**Comment by Ekryd** [comment]
Det går att ta bort spelare via admingränssnittet och det bör räcka, däremot måste vi ha tester som verifierar att historik inte crashar om en spelare tas bort

**Comment by askeew** [comment]
Hur kommer man åt admingränssnittet?

**Comment by Ekryd** [comment]
https://appengine.google.com/

Den 13 november 2011 22:49 skrev askeew <
reply@reply.github.com

**Comment by Ekryd** [comment]
Har börjat skapa tester för det här.

**Comment by Ekryd** [comment]
Fixat. I och med version 12 ska användare kunna tas bort från admingränssnittet. Dessutom finns det servicemetod för att ta bort användare, men den är inte tillgänglig för GUI (ännu).

**Comment by jj71** [comment]
Kommer inte åt admingränssnittet.

**Comment by Ekryd** [comment]
Jag tar bort användare och stänger issue själv

Med vänliga hälsningar
/Björn

26 dec 2011 kl. 10:44 skrev Jimmy Johanssonreply@reply.github.com:

**Comment by jj71** [comment]
Ok, ta bort alla nollor :)

**Comment by Ekryd** [comment]
Nollorna är borta och applikationen verkar snurra på

**Comment by jj71** [comment]
Bara de två supernollorna kvar... :)
