### ISSUE TITLE
Less calls when refreshing

### ISSUE THREAD

**Issue by Ekryd** [Ekryd/Vinnarstegen#2]
The refresh function reloads lots of lists every minute. It should be sufficient to check if something has changed on the server  before reloading everything. If this isn't corrected, it will cost money to run the application on App Engine.

**Comment by Ekryd** [comment]
Fixed a refresh function that checks if anything has changed on the server before reloading everything. Major rewrite of refresh functionality, but no changes i GUI. Fixed in version 11

**Comment by jj71** [comment]
Svårt att verifiera denna. Ser att knappen under fliken "Meddelanden" ändras 1 ggr / minut. Hur påverkar detta refresh-funktionen? Annars ser allt ut att fungera som det ska.

**Comment by Ekryd** [comment]
Meddelandeknappen är en så kallad client-refresh, så då går inga anrop mot servern. När listor uppdaterats pga andra användares kommandon, så ska förändringarna laddas inom en minut.

**Comment by jj71** [comment]
Ok, hur verifierar vi att detta fungerar? Jag har skickat en utmaning och lagt ett par kommentarer under Meddelanden och dessa förändringar slår igenom på en gång. Kan vi anse att det är verifierat då? Givetvis inte heltäckande men om refresh-funktionen är samma överallt så tycks den fungera.

**Comment by Ekryd** [comment]
Det ska slå igenom för en annan användare utan att han rör refresh-knappen. 

Med vänliga hälsningar
/Björn

9 nov 2011 kl. 23:15 skrev Jimmy Johanssonreply@reply.github.com:

**Comment by jj71** [comment]
Allt fungerar som det ska.
