### ISSUE TITLE
Profile page for each player

### ISSUE THREAD

**Issue by Ekryd** [Ekryd/Vinnarstegen#21]
En spelare ska kunna se en översiktssida över andra spelare för att få mer detaljerad information om den spelaren.

Minimum information om en spelare är:
- Alias
- Riktig emailaddress
- Knapp för utmaning
- Knapp för registrering av vinst och förlust

Knapparna tas då bort från poängsidan.

Jimmy, 
fler minimumfält? (-Hur lite? -Som personalomsorg på en myndighet!) 
ett designförslag (fält, navigering mm)?

**Comment by jj71** [comment]
Spånar lite
- Vänster- eller högerhänt
- Rack (stomme, gummin)
- Meriter (idrottsliga)
- Spelarbild
- Motto
