### ISSUE TITLE
enforca regler

### ISSUE THREAD

**Issue by askeew** [Ekryd/Vinnarstegen#24]
reglerna säger att man bara kan utmana max 3 steg upp. Men applikationen tillåter att man utmanar vem som helst. Vi borde styra så applikationen endast tillåter det vi har i reglerna. 

admingui vore intressant för att ställa in parametrar som  t ex "max 3 steg upp"-regeln

**Comment by askeew** [comment]
Dessa två regler borde enforcas av stegen. 
1. Till detta gäller att man endast får utmana någon som ligger 3 steg upp. 
2. Man får endast tacka nej till en utmaning 1 gång. Vid ett andra nekande räknas matchen förlorad med 3-0.

**Comment by Ekryd** [comment]
Kan inte göras som stegen ser ut nu.
