### ISSUE TITLE
nytt krav: enforca utmaningsreglerna

### ISSUE THREAD

**Issue by askeew** [Ekryd/Vinnarstegen#29]
man ska bara kunna säga att man vunnit/förlorat till någon som man har utmanat/blivit utmanad av

**Comment by Ekryd** [comment]
Nah! Föreslår reject. Det ska gå att direkt mata in matchresultat. Om man träffas några stycken och lirar några matcher, så ska man inte behöva lägga in utmaningar efteråt bara för att lägga in resultat.

**Comment by jj71** [comment]
Håller med Björn.

**Comment by askeew** [comment]
Ok. Stäng den

Vänligen Askia

6 dec 2011 kl. 22:32 skrev "Jimmy Johansson" reply@reply.github.com:
