### ISSUE TITLE
Förändra flikinformation

### ISSUE THREAD

**Issue by askeew** [Ekryd/Vinnarstegen#32]
Poängställning:
Jag vill ta bort kolumnerna Senast ändrad och Ändrad av.  Det är irrelevant information. Admin kan ta fram med SQL om nödvändigt.

Meddelanden:
Byt namn på flik meddelanden till klotterplank eller anslagstavla

Samt att vi tar bort de dynamiska knappnamnen. Det borde stå "skicka meddelande".

Jag tycker inte den featuren ger något mervärde. Samt att det ibland står en sak på knappen och men texten man skickar är en annan.

Samt ta bort kolumnen datum och utfört av, den tillför inget, man ser ju i ordningen vilken relation den har till andra meddelanden. Det är för detaljerad infomraiton. samt vem det är som skrivit den kommer med i själva meddelandet

Matcher:
ändra kolumnordningen, 
match, utfört av, datum

Inloggning:
Ta bort, det ger inget mervärde och vi får massa onödiga flikar
Admin kan ta fram med SQL om nödvändigt.

 Övrigt:
se inloggning

Less is more!

**Comment by jj71** [comment]
Många ärenden i samma issue. Tycker det är bättre med 1-1 mappning mellan issue och defekt/change.

**Comment by askeew** [comment]
Jag tycker att det kan bli fr spretigt med en issue per flik s det r bra med en samlings issue som den hr.
Hade du ngra kommentarer p innehllet av kravet och br vi realisera det?

**Comment by jj71** [comment]
Ok, vi har olika åsikter. Tycker ett problem per issue är bäst, särskilt om det blir många kommentarer, det kommer att bli rörigt...

Poängställning:
Inte helt överens. Vänta och se tills du använt stegen ett tag. Underskatta inte tid och vem som gjort vad. Det kan nog bli rörigt om många spelar samtidigt. Att be admin köra SQL för att få svar på frågor är inte bra användbarhet. 

Meddelanden:
Jag tycker också att ett namnbyte kan vara på sin plats, till vad vet jag dock inte just nu.
Tycker inte datum skall tas bort för meddelanden, man vill alltid veta när någon sagt något, i alla fall jag.
Utfört av blir överflödigt eftersom meddelandet alltid börjar med namnet på den som gjort inlägget.

Matcher:
Är benägen att hålla med dig Askia. Önskar också en tydligare matchloggrad, det finns en separat issue på det.

Inloggning och Övrigt:
Vet inte hur intressant det är att se inloggningen. Däremot kan det vara till hjälp att se utmaningar. Föreslår att vi, initialt, slår ihop de båda flikarna till en och kallar den Händelser.
Har ni som utvecklare någon nytta av att se inloggningar?

**Comment by askeew** [comment]
matcher: här saknas viktig information om slutresultatet, ex:
Askia vann över Jimmy med 3-1 och ökade sina poäng från 14 till 18.

**Comment by jj71** [comment]
Så här kanske?
Askia vann över Jimmy med 3-1 och ökade sina poäng från 14 till 18. Jimmy fick 1 poäng.

**Comment by Ekryd** [comment]
Eftersom den här är ihopklumpad så kommer den vara beroende av #21

**Comment by Ekryd** [comment]
Har inget konto (ska jag ha ett tom konto hos dig?). r det inte bttre att
du skickar en pull request?

MVH
/Bjrn

Den 19 december 2011 22:35 skrev askeew <
reply@reply.github.com

**Comment by jj71** [comment]
Meddelandefliken OK.
