### ISSUE TITLE
Byt namn på flik meddelanden till klotterplank eller anslagstavla

### ISSUE THREAD

**Issue by askeew** [Ekryd/Vinnarstegen#33]
Byt namn på flik meddelanden till klotterplank eller anslagstavla

Samt att vi tar bort de dynamiska knappnamnen. Det borde stå "skicka meddelande". 

Jag tycker inte den featuren ger något mervärde. Samt att det ibland står en sak på knappen och men texten man skickar är en annan.

**Comment by jj71** [comment]
Jag tycker också att fliken Meddelande borde byta namn. Är inte helt på det klara vad som borde stå istället, återkommer med det.

Det är en kul feature med dynamiska knappar men jag kan samtidigt hålla med Askia.
Tycker inte knappen ska heta "Skicka meddelande", När man klickar på knappen så kommer det ju upp ett fönster där man först måste skriva meddelandet/kommentaren/inlägget... som man sedan skickar. Vad är Internet-standard? Borde det inte stå ex. "Skriv meddelande", "Skriv inlägg", "Kommentera", "Kommentar", "Klottra", el. likn. lite beroende på vad fliken heter.

**Comment by jj71** [comment]
Oj, varför var den stängd? Bra om man skriver varför man stänger eller förändrar status på en issue.

**Comment by askeew** [comment]
det borde jag gra, men jag la in den i en samlings issue som tar upp allt med flikarna istllet. blir fr rrigt med en issue per flik d det r s mnga flikar

**Comment by askeew** [comment]
stänger denna då issue 32 tar upp det som står här
