### ISSUE TITLE
Matchrapportering - möjlighet för annan/alla att uppdatera matchresultaten

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#5]
Möjlighet för någon annan/alla andra än de som har spelat att uppdatera resultaten. Eftersom det är viktigt att matcherna rapporteras i rätt ordning behöver vi denna möjlighet då alla inte är lika skötsamma med rapporteringen.

**Comment by Ekryd** [comment]
Vilket är bäst; att alla får ändra varandras eller att det finns en admin-roll. Har vi en admin-roll skulle den personen kunna få rättighet att göra undo på allas kommandon.

**Comment by jj71** [comment]
Min första tanke var att alla skulle få ändra varandras men kanske är det bäst med en admin-roll.
Tänker mig två lösningar:
1. Användare med mer rättigheter
2. Ett särskilt admin-konto.
Kan tycka att det skulle vara bättre med ett särskilt admin-konto. Det finns för- och nackdelar med båda lösningarna.
Vad har du för åsikt?

**Comment by askeew** [comment]
Jag håller med. Jag tycker bara de två som spelat kan regga + de med adminroll/den med adminroll

**Comment by Ekryd** [comment]
I viss mån beroende av issue #7
