### ISSUE TITLE
Sortering - annan sortering av ranking

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#6]
Annan sortering av ranking vid lika poäng. Nu sker sortering efter alfabetisk ordning. Vid lika poäng bör den som spelade senast placeras högre upp.

**Comment by Ekryd** [comment]
Ska titta på det här

**Comment by Ekryd** [comment]
Fixat i version 11. Sortering är först på poäng och sedan på ändringsdatum.

**Comment by jj71** [comment]
frisbeepeter och MagnusBrolin har båda 4 poäng och ranking 4.
frisbeepeter spelade senast och är placerad över MagnusBrolin, alltså högre upp.
Alltså OK. Frågan är dock, ska MagnusBrolin rankas som 5:a?
Jag anser att denna issue är verifierad med avseende på det ursprungliga problemet och skapar en ny där den uppkomna frågeställningen tas upp.

**Comment by Ekryd** [comment]
Hmm. Samma poäng = samma ranking

Med vänliga hälsningar
/Björn

9 nov 2011 kl. 19:05 skrev Jimmy Johanssonreply@reply.github.com:

**Comment by jj71** [comment]
Jag förstår hur du tänker men vad är nyttan av att någon ska placeras över någon annan vid lika poäng om de ändå har samma ranking? Då kan man ju lika gärna sortera efter bokstavsordning vid lika poäng. Eller?
Man måste givetvis göra ett undantag för alla som har 0 poäng. Vid varje nollning av stegen måste alla kunna möta alla.
Om samma poäng ger samma ranking kan man då ha två stegettor? Om vi introducerar 3-stegsbegränsningen vid utmaningar tror jag att man som utvecklare blir lite gladare om det är 1-1 förhållande mellan spelare och rankingpoäng.

**Comment by Ekryd** [comment]
Tillfredsstllelsen att faktiskt ligga lite hgre i listan trots att
rankingen r densamma.

Ser nog att ranking r helt baserat p pongen, och den r den som ligger
till grund fr utmaningarna. Dremot ska
man mrka att man glider ned i listan om man r inaktiv. En spelare som har
noll pong, men nd utmanar
(och frlorar matcher) ska ligga hgre i listan n dom som inte gr
ngonting.

Ja, det gr att ha tv spelare som r rankade nr 1, dvs dom r lika bra
spelar-mssigt. Du ska inte ha hgre ranking bara fr att din match
spelades senare (tnk turnering).

MVH
/Bjrn

Den 9 november 2011 21:15 skrev Jimmy Johansson <
reply@reply.github.com>:

**Comment by jj71** [comment]
Var är dina åäö?

Ska spelare med samma poäng räknas som ett steg då?

Menar du att en passiv spelare med högre poäng ska kunna ligga under en aktiv spelare med lägre poäng?
Bäst är nog i så fall att man förlorar poäng om man är passiv, annars blir det knepigt.

Turneringstänk är inte applicerbart, alla spelar inte lika många matcher och alla möter inte alla.
Tänk friidrott. Om du tangerar ett världsrekord är du den gällande världsrekordinnehavaren.

Eftersom två ettor inte kan ha samma poäng efter ett möte sinsemellan måste en utav dem ha spelat minst en senare match. Alltså kan man anse den som mer aktiv och bör premieras.

**Comment by Ekryd** [comment]
Ring mig ;-)

**Comment by jj71** [comment]
Hor av mig sa fort jag ar tillbaka fran USA.
