### ISSUE TITLE
Add role viewer

### ISSUE THREAD

**Issue by Ekryd** [Ekryd/Vinnarstegen#7]
In order to show outside users what vinnarstegen is all about, they should be able to view the scoreboard without joining stegen.

**Comment by jj71** [comment]
Mycket bra idé! Vad vill du att jag ska göra?

**Comment by askeew** [comment]
Den här skulle vara bra att ha så folk kan se hur det går för deltagarna i stegen. Björn. ska vi diskutera denna tekniskt?

**Comment by Ekryd** [comment]
r mer intresserad av kraven frst.
r den en annan kategori anvndare?
Vilka funktioner/tabbar ska do kunna titta p?
Krvs det registrering/inbjudan?
Kan man uppgradera till spelarstatus?
Kan en inaktiv spelare nedgraderas till viewer?

Och framfr allt, vad r syftet med att ha en viewer?

Den 23 november 2011 21:48 skrev askeew <
reply@reply.github.com

**Comment by askeew** [comment]
Syftet är:
Om du är anställd av Skandia/Polisen men inte är med i stegen och vill se hur bra din skrytige/blygsamma kollega är ska du kunna se resultatet.

förslag:
Skulle man inte kunna göra en annan webbapp som bara presenterar resultatet rakt upp och ner? pingisstegenresultat.appspot.com som bara läser från pingisstegen.appspots.coms databas... eller ha en annan htmlsida på samma webapp som bara presenterar resultatet.. pingisstegen.appspot.com/resultat.html

> r den en annan kategori anvndare?
> ej inloggad användare
> 
> Vilka funktioner/tabbar ska do kunna titta p?
> endast läsvy av poängtabben som är strippad
> 
> Krvs det registrering/inbjudan?
> nej, endast länk
> 
> Kan man uppgradera till spelarstatus?
> ja, på sedvanligt inloggning med NUP, finns redan på plats
> 
> Kan en inaktiv spelare nedgraderas till viewer?
> N/A eftersom alla är viewers om man går på länken

**Comment by askeew** [comment]
Stegen borde ha stöd för olika roller. Adminrollen ska t ex kunna se inloggningsfliken, medans den fliken stör användare med enbart pingisroll

**Comment by Ekryd** [comment]
Enligt möte:
Visa strippad poängställning. 
Visa strippad resultatsida. 
Visa övrigt med enbart utmaningar. 
(Manuell refresh borde finnas med, ej automatisk (då den kan ta för mycket resurser)).
Inloggning ska inte behövas och registrering ska inte behövas.
Titta på att implementera den som en egen modul. Vi ska återanvända befintliga gui-komponenter och servicar i så står utsträckning som möjligt.

**Comment by askeew** [comment]
kan du förklara sista inlägget mer i detalj då jag nu är redo att börja beta på denna issue.

Är det så att om jag går till stegens huvudsida och jag inte är inloggad så ska jag se allt fast i en strippad version? Jag är alltså då i en annan modul och när jag loggar in så kommer jag till den riktiga modulen. 

Vi vill ju inte införa en massa:
if( inloggad ) 
   show this 
else 
   show that 

tänker jag mig.

**Comment by Ekryd** [comment]
Tänker mig att man går till annan webbsida. Det borde vara att göra nya presenters. Är i Thailand för tillfället, snacka mer när jag kommer hem?

Med vänliga hälsningar
/Björn

27 jan 2012 kl. 13:56 skrev askeewreply@reply.github.com:
