### ISSUE TITLE
Poängsnitt - ett annat sätt att visa hur bra någon är

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#8]
Önskemål om att visa hur bra en spelare är förutom placeringen i stegen. Ett sätt skulle vara att visa hur många poäng denne spelare i genomsnitt tar/match. Detta snitt skulle, i dagsläget, kunna visas i en egen kolumn under fliken Poängställning.

**Comment by Ekryd** [comment]
Beroende av #21
