### ISSUE TITLE
Utmaningar - med gällande reglerna implementerade

### ISSUE THREAD

**Issue by jj71** [Ekryd/Vinnarstegen#9]
Att man kan göra/sköta utmaningar i vinnarstegen, med de gällande reglerna implementerade. Ex. ska inte kunna utmana någon som ligger mer än tre steg upp.

**Comment by jj71** [comment]
Ser ut att fungera för mig. Jag kan inte utmana någon som ligger mer än tre steg efter mig. Nu ligger jag rankad som nummer 1 vilket gör att jag inte kan verifiera åt andra hållet. Askia kan du kolla så att det funkar åt andra hållet? Hur är det implementerat, går det efter ranking, så att alla med samma poäng räknas som om de ligger på samma plats?

**Comment by Ekryd** [comment]
Det går efter ranking. Jag kan utmana Tord, frisbeepeter och MagnusBrolin, samt alla andra som också har 0 poäng. Stäng den.
